#
# This is a generated file.
#

api.version=v1.0
batch.engine.entity.class.name=task.rest.dto.v1_0.Task
batch.engine.task.item.delegate=true
batch.planner.export.enabled=false
batch.planner.import.enabled=true
entity.class.name=task.rest.dto.v1_0.Task
osgi.jaxrs.application.select=(osgi.jaxrs.name=TaskRest)
osgi.jaxrs.resource=true
auth.verifier.guest.allowed=true
auth.verifier.oauth2.enabled=true
